<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-04-11
 * Time: 10:31
 */

namespace common\components;


use yii\web\Controller;

class BaseController extends Controller
{
    //public $layout = '@app/views/layouts/main';
    public $pageSize = 15;
    public $data = ['js'=>[], 'css'=>[], 'submit'=>0, 'action_list'=>'index'];
    const  CODE_ERR = '400';
    const  CODE_SUC = '200';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['module_id'] = $this->module->id;

        $this->data['controller_id'] = $this->id;
        $this->data['submit'] = \Yii::$app->request->get('ref_sub', '0');


    }
}